AppBundle\Entity\City:
    type: entity
    table: City
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        state:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
    lifecycleCallbacks: {  }
