AppBundle\Entity\Dadosfinais:
    type: entity
    table: dadosfinais
    indexes:
        codigoIdentificacao:
            columns:
                - codigoIdentificacao
    id:
        codigodadosfinais:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigoDadosFinais
            generator:
                strategy: IDENTITY
    fields:
        impressaoclinica:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: impressaoClinica
        diagnosticofinal:
            type: boolean
            nullable: true
            column: diagnosticoFinal
        diagnosticofinalds:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: diagnosticoFinalDs
    manyToOne:
        codigoidentificacao:
            targetEntity: Identificacao
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoIdentificacao:
                    referencedColumnName: codigoIdentificacao
            orphanRemoval: false
    lifecycleCallbacks: {  }
