AppBundle\Entity\DadosescolaresEvolucaoneuropsicomotora:
    type: entity
    table: dadosescolares_evolucaoneuropsicomotora
    indexes:
        codigoIdentificacao:
            columns:
                - codigoIdentificacao
        codigoEscolaridade:
            columns:
                - codigoEscolaridade
    id:
        codigoevolucaoneuropsicomotora:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigoEvolucaoNeuropsicomotora
            generator:
                strategy: IDENTITY
    fields:
        entrouescola:
            type: boolean
            nullable: true
            column: entrouEscola
        repetencias:
            type: boolean
            nullable: true
        numerorepetencias:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: numeroRepetencias
        sorrisosocial:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: sorrisoSocial
        sustentoucabeca:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: sustentouCabeca
        sustentousemapoio:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: sustentouSemApoio
        ficouempe:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: ficouEmPe
        engatinhou:
            type: float
            nullable: true
            precision: 10
            scale: 2
        andou:
            type: float
            nullable: true
            precision: 10
            scale: 2
        sons:
            type: float
            nullable: true
            precision: 10
            scale: 2
        frases:
            type: float
            nullable: true
            precision: 10
            scale: 2
        controleesfincteriano:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: controleEsfincteriano
        palavras:
            type: float
            nullable: true
            precision: 10
            scale: 2
    manyToOne:
        codigoidentificacao:
            targetEntity: Identificacao
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoIdentificacao:
                    referencedColumnName: codigoIdentificacao
            orphanRemoval: false
        codigoescolaridade:
            targetEntity: Escolaridade
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoEscolaridade:
                    referencedColumnName: codigoEscolaridade
            orphanRemoval: false
    lifecycleCallbacks: {  }
