AppBundle\Entity\Drogas:
    type: entity
    table: drogas
    id:
        codigodrogas:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigoDrogas
            generator:
                strategy: IDENTITY
    fields:
        nomedroga:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: nomeDroga
    lifecycleCallbacks: {  }
