AppBundle\Entity\Drogasusadas:
    type: entity
    table: drogasusadas
    indexes:
        codigoDrogas:
            columns:
                - codigoDrogas
        codigoHistorico:
            columns:
                - codigoHistorico
    id:
        codigodrogausada:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigoDrogaUsada
            generator:
                strategy: IDENTITY
    fields:
        drogadescricao:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: drogaDescricao
        primeiromesgestacaousodroga:
            type: boolean
            nullable: true
            column: primeiroMesGestacaoUsoDroga
        segundomesgestacaousodroga:
            type: boolean
            nullable: true
            column: segundoMesGestacaoUsoDroga
        terceiromesgestacaousodroga:
            type: boolean
            nullable: true
            column: terceiroMesGestacaoUsoDroga
        quartomesgestacaousodroga:
            type: boolean
            nullable: true
            column: quartoMesGestacaoUsoDroga
        quintomesgestacaousodroga:
            type: boolean
            nullable: true
            column: quintoMesGestacaoUsoDroga
        sextomesgestacaousodroga:
            type: boolean
            nullable: true
            column: sextoMesGestacaoUsoDroga
        setimomesgestacaousodroga:
            type: boolean
            nullable: true
            column: setimoMesGestacaoUsoDroga
        oitavomesgestacaousodroga:
            type: boolean
            nullable: true
            column: oitavoMesGestacaoUsoDroga
        nonomesgestacaousodroga:
            type: boolean
            nullable: true
            column: nonoMesGestacaoUsoDroga
        naoseimesgestacaousodroga:
            type: boolean
            nullable: true
            column: naoSeiMesGestacaoUsoDroga
    manyToOne:
        codigodrogas:
            targetEntity: Drogas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoDrogas:
                    referencedColumnName: codigoDrogas
            orphanRemoval: false
        codigohistorico:
            targetEntity: Historicogestacaoneonatal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoHistorico:
                    referencedColumnName: codigoHistorico
            orphanRemoval: false
    lifecycleCallbacks: {  }
