AppBundle\Entity\Examefisico:
    type: entity
    table: examefisico
    indexes:
        codigoIdentificacao:
            columns:
                - codigoIdentificacao
    id:
        codigoexamefisico:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigoExameFisico
            generator:
                strategy: IDENTITY
    fields:
        olhosalterado:
            type: boolean
            nullable: true
            column: olhosAlterado
        olhosalteradodescricao:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: olhosAlteradoDescricao
        narizalterado:
            type: boolean
            nullable: true
            column: narizAlterado
        narizalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: narizAlteradoDs
        bocaalterado:
            type: boolean
            nullable: true
            column: bocaAlterado
        bocaalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: bocaAlteradoDs
        pescocoalterado:
            type: boolean
            nullable: true
            column: pescocoAlterado
        pescocoalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: pescocoAlteradoDs
        toraxalterado:
            type: boolean
            nullable: true
            column: toraxAlterado
        toraxalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: toraxAlteradoDs
        abdomenalterado:
            type: boolean
            nullable: true
            column: abdomenAlterado
        abdomenalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: abdomenAlteradoDs
        genitaliaalterado:
            type: boolean
            nullable: true
            column: genitaliaAlterado
        genitaliaalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: genitaliaAlteradoDs
        colunaalterado:
            type: boolean
            nullable: true
            column: colunaAlterado
        colunaalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: colunaAlteradoDs
        membrossuperioresalterado:
            type: boolean
            nullable: true
            column: membrosSuperioresAlterado
        membrossuperioresalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: membrosSuperioresAlteradoDs
        membrosinferioresalterado:
            type: boolean
            nullable: true
            column: membrosInferioresAlterado
        membrosinferioresalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: membrosInferioresAlteradoDs
        peleefanerosalterado:
            type: boolean
            nullable: true
            column: peleeFanerosAlterado
        peleefanerosalteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: peleeFanerosAlteradoDs
        exameneurologico:
            type: boolean
            nullable: true
            column: exameNeurologico
        peso:
            type: float
            nullable: true
            precision: 10
            scale: 2
        pesoalterado:
            type: boolean
            nullable: true
            column: pesoAlterado
        estatura:
            type: float
            nullable: true
            precision: 10
            scale: 2
        distintercinterna:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: distIntercInterna
        distintercexterna:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: distIntercExterna
        compmao:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: compMao
        compdedomedio:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: compDedoMedio
        perimetrocefalico:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: perimetroCefalico
        perimetrocefalicoalterado:
            type: boolean
            nullable: true
            column: perimetroCefalicoAlterado
        distintercexternaalterado:
            type: boolean
            nullable: true
            column: distIntercExternaAlterado
        compmaoalterado:
            type: boolean
            nullable: true
            column: compMaoAlterado
        compdedomedioalterado:
            type: boolean
            nullable: true
            column: compDedoMedioAlterado
        pesodescricaoalterado:
            type: boolean
            nullable: true
            column: pesoDescricaoAlterado
        estaturadescricaoalterado:
            type: boolean
            nullable: true
            column: estaturaDescricaoAlterado
        perimetrocefalicodescricaoalterado:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: perimetroCefalicoDescricaoAlterado
        distintercinternadescricaoalterado:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: distIntercInternaDescricaoAlterado
        compdedomediodescricaoalterado:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: compDedoMedioDescricaoAlterado
        compmaodescricaoalterado:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: compMaoDescricaoAlterado
        aspectogeral:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: aspectoGeral
        cranioefacealterado:
            type: boolean
            nullable: true
            column: cranioeFaceAlterado
        cranioefacealteradodescricao:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: cranioeFaceAlteradoDescricao
        distintercexternadescricaoalterado:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: distIntercExternaDescricaoAlterado
        estaturaalterado:
            type: boolean
            nullable: true
            column: estaturaAlterado
        distintercinternaalterado:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: distIntercInternaAlterado
        cranioalterado:
            type: boolean
            nullable: true
            column: cranioAlterado
        cranioalteradodescricao:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: cranioAlteradoDescricao
    manyToOne:
        codigoidentificacao:
            targetEntity: Identificacao
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoIdentificacao:
                    referencedColumnName: codigoIdentificacao
            orphanRemoval: false
    lifecycleCallbacks: {  }
