AppBundle\Entity\Examesrealizados:
    type: entity
    table: examesrealizados
    indexes:
        codigoExame:
            columns:
                - codigoExame
        codigoIdentificacao:
            columns:
                - codigoIdentificacao
    id:
        codigoexamerealizado:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigoExameRealizado
            generator:
                strategy: IDENTITY
    fields:
        resultadoexame:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: resultadoExame
        examealterado:
            type: boolean
            nullable: true
            column: exameAlterado
        idadeatualpaciente:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: idadeAtualPaciente
        dataexame:
            type: date
            nullable: true
            column: dataExame
        examealteradods:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: exameAlteradoDs
    manyToOne:
        codigoexame:
            targetEntity: Listaexames
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoExame:
                    referencedColumnName: codigoExame
            orphanRemoval: false
        codigoidentificacao:
            targetEntity: Identificacao
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoIdentificacao:
                    referencedColumnName: codigoIdentificacao
            orphanRemoval: false
    lifecycleCallbacks: {  }
