AppBundle\Entity\Listaexames:
    type: entity
    table: listaexames
    id:
        codigoexame:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigoExame
            generator:
                strategy: IDENTITY
    fields:
        nomeexame:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: nomeExame
    lifecycleCallbacks: {  }
