AppBundle\Entity\Medicamentosusados:
    type: entity
    table: medicamentosusados
    indexes:
        codigoHistorico:
            columns:
                - codigoHistorico
        codigoMedicamento:
            columns:
                - codigoMedicamento
    id:
        codigomedicamentousado:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigoMedicamentoUsado
            generator:
                strategy: IDENTITY
    fields:
        medicamentodescricao:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: medicamentoDescricao
        medicamentomesgestacaouso:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: medicamentoMesGestacaoUso
        primeiromesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: primeiroMesMedicamentoGestacaoUso
        segundomesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: segundoMesMedicamentoGestacaoUso
        terceiromesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: terceiroMesMedicamentoGestacaoUso
        quartomesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: quartoMesMedicamentoGestacaoUso
        quintomesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: quintoMesMedicamentoGestacaoUso
        sextomesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: sextoMesMedicamentoGestacaoUso
        setimomesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: setimoMesMedicamentoGestacaoUso
        oitavomesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: oitavoMesMedicamentoGestacaoUso
        nonomesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: nonoMesMedicamentoGestacaoUso
        naoseimesmedicamentogestacaouso:
            type: boolean
            nullable: true
            column: naoSeiMesMedicamentoGestacaoUso
    manyToOne:
        codigohistorico:
            targetEntity: Historicogestacaoneonatal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoHistorico:
                    referencedColumnName: codigoHistorico
            orphanRemoval: false
        codigomedicamento:
            targetEntity: Medicamentos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigoMedicamento:
                    referencedColumnName: codigoMedicamento
            orphanRemoval: false
    lifecycleCallbacks: {  }
