AppBundle\Entity\User:
    type: entity
    table: User
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
    lifecycleCallbacks: {  }
