AppBundle\Entity\Usuarios:
    type: entity
    table: usuarios
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
    id:
        codigousuario:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            id: true
            column: codigoUsuario
            generator:
                strategy: IDENTITY
    fields:
        usuario:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        senha:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        tipo:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
